### ISSUE TITLE
Performance Issue in filter_perms_queryset_by_objects

### ISSUE THREAD

**Issue by kmmbvnr** [kmmbvnr/django-guardian-ng#2]
Original issue: https://github.com/django-guardian/django-guardian/issues/811

**Comment by kmmbvnr** [comment]
The original code change caused the issue

https://github.com/django-guardian/django-guardian/commit/1c74f2491bd5aba21c8fa9fdcf3cd1cc5c007382

Discussion:

https://github.com/django-guardian/django-guardian/issues/189

**Comment by cmaggiulli** [comment]
Nice.  We have a variety of other performance related issues we’ve patched in our private fork. Mostly around issues with the direct foreign key implementation.  Are you interested in those?
