### ISSUE TITLE
How does a non-superuser give object permission to another non-superuser

### ISSUE THREAD

**Issue by kmmbvnr** [kmmbvnr/django-guardian-ng#35]
Original issue: https://github.com/django-guardian/django-guardian/issues/762

**Comment by kmmbvnr** [comment]
- [ ] reproduce
- [ ] restrict permission change to a user with change permission

**Comment by kmmbvnr** [comment]
Can't reproduce. The View permission sends me back to the admin index

**Comment by adnannazir** [comment]
This issue is there. If a user is granted access to view an object, he can assign himself or anyother user other permissions as well.
